name = input("Enter name: ")
Class = input("Enter class: ")
section = input("Enter section: ")
USN = input("Enter USN: ")
print("Hello ")
print("My Name is: ", name)
print("I am from Class:", Class)  
print("Section:", section)
print("USN:", USN)